// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-7FRrVqdhBk0eVWRspuBwk_Lw1wIYU6E',
    appId: '1:829481464602:web:c5278b16200021a8ea32a3',
    messagingSenderId: '829481464602',
    projectId: 'do-nest-app',
    authDomain: 'do-nest-app.firebaseapp.com',
    storageBucket: 'do-nest-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8wnYdYFehtljhgA9-vyINcZKZOplABL0',
    appId: '1:829481464602:android:072de25537716b45ea32a3',
    messagingSenderId: '829481464602',
    projectId: 'do-nest-app',
    storageBucket: 'do-nest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDud5naQGL3WJHKFIjIUDG4Ev5Rfc4kaAI',
    appId: '1:829481464602:ios:88a56f9cb275a989ea32a3',
    messagingSenderId: '829481464602',
    projectId: 'do-nest-app',
    storageBucket: 'do-nest-app.firebasestorage.app',
    iosBundleId: 'com.example.doNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDud5naQGL3WJHKFIjIUDG4Ev5Rfc4kaAI',
    appId: '1:829481464602:ios:88a56f9cb275a989ea32a3',
    messagingSenderId: '829481464602',
    projectId: 'do-nest-app',
    storageBucket: 'do-nest-app.firebasestorage.app',
    iosBundleId: 'com.example.doNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-7FRrVqdhBk0eVWRspuBwk_Lw1wIYU6E',
    appId: '1:829481464602:web:3c665a8e696c73d9ea32a3',
    messagingSenderId: '829481464602',
    projectId: 'do-nest-app',
    authDomain: 'do-nest-app.firebaseapp.com',
    storageBucket: 'do-nest-app.firebasestorage.app',
  );
}
